openapi: 3.0.1
info:
  title: Book API
  description: API to manage books (get and create books).
  version: 1.0.0
paths:
  /books/:
    get:
      summary: Get a list of books
      description: Retrieve all books from the system.
      operationId: listBooks
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Book'
        '404': 
          description: No books found
        '500':
          description: Internal server error

  /books/{bookId}:
    get:
      summary: Get a book by ID
      description: Retrieve a book from the system.
      operationId: getBookById
      parameters:
        - name: bookId
          in: path
          required: true
          description: The ID of the book to retrieve.
          schema:
            type: number
      responses:
        200:
          description: A Book by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        404:
          description: Not found
        500:
          description: Internal server error
components:
  schemas:
    Book:
      type: object
      required:
        - id
        - title
        - author
      properties:
        id:
          type: number
          description: unique id of book
        title:
          type: string
          description: title of the book
        author:
          type: string
          description: Author of the book
        description:
          type: string
          description: decription of the book
